//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testCSOMapp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebPartResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebPartResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("testCSOMapp.WebPartResources", typeof(WebPartResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;WebPart xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://schemas.microsoft.com/WebPart/v2&quot;&gt;
        ///  &lt;Title&gt;Content Editor&lt;/Title&gt;
        ///  &lt;FrameType&gt;None&lt;/FrameType&gt;
        ///  &lt;Description&gt;Allows authors to enter rich text content.&lt;/Description&gt;
        ///  &lt;IsIncluded&gt;true&lt;/IsIncluded&gt;
        ///  &lt;ZoneID&gt;Header&lt;/ZoneID&gt;
        ///  &lt;PartOrder&gt;0&lt;/PartOrder&gt;
        ///  &lt;FrameState&gt;Normal&lt;/FrameState&gt;
        ///  &lt;Height /&gt;
        ///  &lt;Width /&gt;
        ///  &lt;AllowRemove&gt;true&lt;/AllowR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CEWPtest {
            get {
                return ResourceManager.GetString("CEWPtest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11235125.
        /// </summary>
        internal static string DocumentsWebPart {
            get {
                return ResourceManager.GetString("DocumentsWebPart", resourceCulture);
            }
        }
    }
}
